# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55b99082b6c740af04a82acdfa3b44138c3a8a883bc62d4afa2159a43eb2b9769915e674a9efdaef599c8ab396b59c843da38f25bb8529b661e9ea22a4c14a43

test:
  secret_key_base: 93dd6e3b0d66828264da3d28ec7ef9ef035cf5a136a76e58a894310a9fa297ed31b24503dccf8fdab3d2184aa109d81495070724d5f3b0ba0ba4b50fd6f48065

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
